apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Juice Shop Demo Workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  test:
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1
      - name: Simple test step
        uses: docker://alpine:latest
        run: |
          echo "🧪 Running basic tests..."
          echo "✅ Test 1: Application structure check - PASSED"
          echo "✅ Test 2: Configuration validation - PASSED"
          echo "✅ Test 3: Security baseline - PASSED"
          echo "📊 All tests completed successfully"
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Test Results Summary
            
            ✅ **Application Structure Check**: PASSED  
            ✅ **Configuration Validation**: PASSED  
            ✅ **Security Baseline**: PASSED  
            
            **Total Tests**: 3  
            **Passed**: 3  
            **Failed**: 0  
            **Coverage**: 100%
          format: MARKDOWN

  build:
    needs: test
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1
      - name: Simulate build
        uses: docker://alpine:latest
        run: |
          echo "🔨 Building Juice Shop Demo..."
          echo "📦 Creating application package..."
          echo "🏗️  Compiling assets..."
          echo "✅ Build completed successfully"
          echo "📋 Build artifacts ready for deployment"
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Build Results
            
            ✅ **Application Package**: Created successfully  
            ✅ **Asset Compilation**: Completed  
            ✅ **Build Artifacts**: Ready for deployment  
            
            **Build Status**: SUCCESS  
            **Build Time**: 2m 34s  
            **Artifact Size**: 45.2 MB
          format: MARKDOWN

  deploy:
    needs: build
    steps:
      - name: Simulate deployment
        uses: docker://alpine:latest
        run: |
          echo "🚀 Deploying to Demo Environment..."
          echo "🌐 Setting up virtual infrastructure..."
          echo "📡 Configuring load balancer..."
          echo "🔧 Applying configuration..."
          echo "✅ Deployment completed successfully"
          echo "🔗 Application available at: https://juice-shop-demo.example.com"
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Deployment Completed Successfully
            
            **Environment**: Demo Environment  
            **Status**: ✅ Healthy  
            **URL**: https://juice-shop-demo.example.com  
            
            ### Deployment Details
            - ✅ Infrastructure: Provisioned
            - ✅ Load Balancer: Configured
            - ✅ Application: Running
            - ✅ Health Checks: Passing
            
            **Deployment Time**: 1m 45s  
            **Response Time**: 150ms
          format: MARKDOWN
